import React, { useState } from 'react';
import { AboutSection } from './landing/AboutSection';
import { HowSection } from './landing/HowSection';
import { PlansSection } from './landing/PlansSection';
import { ArrowRight, CheckCircle2, FileText, FlaskConical, GitBranch, GraduationCap, Lightbulb, Menu, Search, ShieldCheck, Sparkles } from 'lucide-react';

export function LandingPage({onLogin,onSignup}) {
  const [menu,setMenu]=useState(false); return <div className="landing-page"><div className="landing-orb orb-one"/><div className="landing-orb orb-two"/><div className="landing-grid"/><nav className="landing-nav"><a className="landing-brand" href="#home"><span><Sparkles size={18}/></span> Research Mentor <small>AI</small></a><div className={`landing-links ${menu?'show':''}`}><a href="#home">Home</a><a href="#about">About us</a><a href="#workflow">How it works</a><a href="#plans">Plans</a><a href="#mentors">Mentors</a></div><div className="landing-actions"><button className="landing-login" onClick={onLogin}>Log in</button><button className="landing-signup" onClick={onSignup}>Sign up <ArrowRight size={15}/></button><button className="landing-menu" onClick={()=>setMenu(!menu)}><Menu size={20}/></button></div></nav>
    <main><section className="landing-hero" id="home"><div className="hero-copy"><div className="eyebrow-pill"><span/> AI-powered research workspace</div><h1>From a <em>research idea</em><br/>to a plan you can defend.</h1><p>Research Mentor AI helps students discover papers, check novelty, identify research gaps, design experiments and draft a source-aware research paper — in one guided workflow.</p><div className="hero-cta"><button className="landing-primary" onClick={onSignup}>Start your research journey <ArrowRight size={17}/></button><button className="landing-secondary" onClick={onLogin}>I already have an account</button></div><div className="hero-proof"><span><ShieldCheck size={15}/> Source-linked outputs</span><span><GitBranch size={15}/> Evidence-backed gaps</span><span><GraduationCap size={15}/> Built for students</span></div></div><div className="hero-dashboard"><div className="floating-tag tag-one"><CheckCircle2 size={14}/> Every paper linked</div><div className="floating-tag tag-two"><Sparkles size={14}/> Novelty score</div><div className="mock-window"><div className="mock-top"><span/><span/><span/><b>Research Mentor AI</b></div><div className="mock-content"><div className="mock-side"><i/><i/><i/><i/><i/></div><div className="mock-main"><div className="mock-kicker">RESEARCH WORKFLOW</div><h3>Your research workspace</h3><div className="mock-pipeline"><span className="active">Explore</span><span className="active">Novelty</span><span>Gaps</span><span>Experiment</span><span>Draft</span></div><div className="mock-cards"><div><small>EXPLORE</small><strong>Analyse your idea, find papers</strong><i style={{width:'76%'}}/></div><div><small>RESEARCH GAPS</small><strong>Evidence for every gap</strong><i style={{width:'58%'}}/></div><div><small>EXPERIMENT PLAN</small><strong>Datasets, baselines, steps</strong><i style={{width:'84%'}}/></div></div></div></div></div></div></section><section className="landing-stats"><div><strong>5</strong><span>connected research tools</span></div><div><strong>10+</strong><span>real papers per search</span></div><div><strong>DOI</strong><span>links to every source</span></div><div><strong>1:1</strong><span>mentor sessions</span></div></section><AboutSection /><HowSection /><PlansSection onSignup={onSignup} /><section className="landing-cta" id="mentors"><div><span>READY TO RESEARCH?</span><h2>Bring your next idea into focus.</h2><p>Create your workspace and follow the workflow one step at a time.</p></div><button onClick={onSignup}>Create your free account <ArrowRight size={17}/></button></section></main><footer className="landing-footer"><div>© 2026 Research Mentor AI</div><div><a href="#about">About</a><a href="#plans">Plans</a><a href="#workflow">How it works</a><button onClick={onLogin}>Log in</button></div></footer></div>;
}
